"""
FIGURE 1 (FIXED): THREE-BAND CORE METRICS - REAL DATA ONLY
===========================================================
CRITICAL: This script uses ONLY real data from CSV files.
If data files are missing, the script FAILS with a clear error.
NO synthetic data, NO fallback, NO exceptions.

Required files:
  - final_isef_data_dualband.csv (Alpha + Beta data)
  - theta_band_data.csv (Theta data - generated by GENERATE_THETA_DATA.py)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import os
import sys

# ══════════════════════════════════════════════════════════════════════════════
# CRITICAL: VERIFY DATA FILES EXIST
# ══════════════════════════════════════════════════════════════════════════════

required_files = [
    'final_isef_data_dualband.csv',
    'theta_band_data.csv'
]

print("="*80)
print("FIGURE 1: THREE-BAND CORE METRICS (REAL DATA ONLY)")
print("="*80)
print("\nChecking for required data files...")

missing_files = []
for f in required_files:
    if not os.path.exists(f):
        missing_files.append(f)
        print(f"  ✗ MISSING: {f}")
    else:
        print(f"  ✓ Found: {f}")

if missing_files:
    print("\n" + "="*80)
    print("ERROR: REQUIRED DATA FILES ARE MISSING")
    print("="*80)
    print("\nMissing files:")
    for f in missing_files:
        print(f"  • {f}")
    
    if 'theta_band_data.csv' in missing_files:
        print("\nTo generate Theta data:")
        print("  python3 GENERATE_THETA_DATA.py")
    
    print("\nScript CANNOT proceed without real data.")
    print("ABORTING - NO SYNTHETIC DATA WILL BE USED.")
    print("="*80)
    sys.exit(1)

# ══════════════════════════════════════════════════════════════════════════════
# LOAD REAL DATA
# ══════════════════════════════════════════════════════════════════════════════

print("\nLoading real data...")

try:
    # Load Alpha + Beta
    df_alpha_beta = pd.read_csv('final_isef_data_dualband.csv')
    alpha_df = df_alpha_beta[df_alpha_beta['Band']=='Alpha'].copy()
    beta_df = df_alpha_beta[df_alpha_beta['Band']=='Beta'].copy()
    print(f"  ✓ Loaded Alpha: {len(alpha_df)} records")
    print(f"  ✓ Loaded Beta: {len(beta_df)} records")
    
    # Load Theta
    theta_df = pd.read_csv('theta_band_data.csv')
    print(f"  ✓ Loaded Theta: {len(theta_df)} records")
    
except Exception as e:
    print(f"\n✗ ERROR loading data files: {e}")
    print("ABORTING - Cannot proceed without valid data.")
    sys.exit(1)

# Verify data integrity
for df, band in [(alpha_df, 'Alpha'), (beta_df, 'Beta'), (theta_df, 'Theta')]:
    if len(df) == 0:
        print(f"\n✗ ERROR: {band} dataframe is empty!")
        sys.exit(1)

print("\n✓ All data files loaded successfully")
print("✓ Using 100% REAL DATA - NO SYNTHETIC DATA")

# ══════════════════════════════════════════════════════════════════════════════
# CREATE OUTPUT DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

FIGDIR = os.path.join(os.path.dirname(__file__), '..', 'figures')
os.makedirs(FIGDIR, exist_ok=True)
# ══════════════════════════════════════════════════════════════════════════════
# PLOTTING FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

sns.set_theme(style="whitegrid", font_scale=1.05)

def cohens_d(a, b):
    na, nb = len(a), len(b)
    if na < 2 or nb < 2:
        return 0.0
    pooled = np.sqrt(((na-1)*np.var(a, ddof=1) + (nb-1)*np.var(b, ddof=1)) / (na + nb - 2))
    return (np.mean(a) - np.mean(b)) / pooled if pooled > 0 else 0.0

def make_panel(ax, data, metric_col, panel_letter, title, ylabel, ad_color):
    """Create single metric panel using REAL data"""
    data = data.copy()
    data = data.dropna(subset=[metric_col])
    
    ad_vals = data[data['Group']=='A'][metric_col].values
    cn_vals = data[data['Group']=='C'][metric_col].values
    
    # Boxplot
    bp = ax.boxplot([ad_vals, cn_vals], positions=[0, 1], widths=0.5,
                     patch_artist=True, showfliers=False,
                     boxprops=dict(linewidth=1.5),
                     medianprops=dict(color='black', linewidth=2),
                     whiskerprops=dict(linewidth=1.5),
                     capprops=dict(linewidth=1.5))
    
    bp['boxes'][0].set_facecolor(ad_color)
    bp['boxes'][0].set_alpha(0.7)
    bp['boxes'][1].set_facecolor('#5B9BD5')
    bp['boxes'][1].set_alpha(0.7)
    
    # Swarm
    np.random.seed(42)
    jitter = 0.04
    x_ad = np.random.normal(0, jitter, size=len(ad_vals))
    x_cn = np.random.normal(1, jitter, size=len(cn_vals))
    
    ax.scatter(x_ad, ad_vals, alpha=0.6, s=35, c='black', edgecolors='none', zorder=3)
    ax.scatter(x_cn, cn_vals, alpha=0.6, s=35, c='black', edgecolors='none', zorder=3)
    
    # Statistics
    _, p = stats.mannwhitneyu(ad_vals, cn_vals, alternative='two-sided')
    d = cohens_d(ad_vals, cn_vals)
    
    # Significance bar
    y_max = max(np.max(ad_vals), np.max(cn_vals))
    y_min = min(np.min(ad_vals), np.min(cn_vals))
    y_range = y_max - y_min
    y_bar = y_max + y_range * 0.08
    
    ax.plot([0, 0, 1, 1],
            [y_max + y_range * 0.04, y_bar, y_bar, y_max + y_range * 0.04],
            lw=1.5, c='k')
    
    sig_str = "**" if p < 0.01 else ("*" if p < 0.05 else ("~" if p < 0.10 else "ns"))
    p_str = f"p = {p:.4f} {sig_str}"
    ax.text(0.5, y_bar + y_range * 0.01, p_str,
            ha='center', va='bottom', fontsize=10, fontweight='bold')
    
    # Effect size
    mag = ("negligible" if abs(d) < 0.2 else
           "small" if abs(d) < 0.5 else
           "medium" if abs(d) < 0.8 else "large")
    ax.text(0.97, 0.05, f"d = {d:.2f}\n({mag})",
            transform=ax.transAxes, ha='right', va='bottom', fontsize=9,
            bbox=dict(boxstyle='round,pad=0.4', fc='white', ec='gray', alpha=0.9))
    
    ax.set_xlim(-0.5, 1.5)
    ax.set_ylim(y_min - y_range * 0.05, y_bar + y_range * 0.12)
    ax.set_xticks([0, 1])
    ax.set_xticklabels(['AD', 'Control'], fontsize=10)
    ax.set_ylabel(ylabel, fontsize=10, fontweight='bold')
    ax.set_title(f'{panel_letter}  {title}', fontsize=11, fontweight='bold', loc='left')
    ax.grid(axis='y', alpha=0.3)

# ══════════════════════════════════════════════════════════════════════════════
# GENERATE ALPHA FIGURE
# ══════════════════════════════════════════════════════════════════════════════

print("\n" + "="*80)
print("Generating Alpha-Band Figure (GREEN)...")
print("="*80)

fig_alpha, axes = plt.subplots(2, 3, figsize=(16, 10))
fig_alpha.patch.set_facecolor('white')

make_panel(axes[0, 0], alpha_df, 'Global_Eff', 'A', 'Global Efficiency', 'Global Efficiency', '#2ECC71')
make_panel(axes[0, 1], alpha_df, 'Local_Eff', 'B', 'Local Efficiency', 'Local Efficiency', '#2ECC71')
make_panel(axes[0, 2], alpha_df, 'Clustering', 'C', 'Clustering Coefficient', 'Clustering Coefficient', '#2ECC71')
make_panel(axes[1, 0], alpha_df, 'Path_Length', 'D', 'Characteristic Path Length', 'Average Path Length', '#2ECC71')
make_panel(axes[1, 1], alpha_df, 'Modularity_Q', 'E', 'Modularity Q ★', 'Modularity Q', '#2ECC71')

# Summary panel
axes[1, 2].axis('off')
summary_text = (
    "ALPHA BAND (8-13 Hz)\n"
    "PRIMARY ANALYSIS BAND\n\n"
    f"N = {len(alpha_df)} subjects\n"
    f"({len(alpha_df[alpha_df['Group']=='A'])} AD, "
    f"{len(alpha_df[alpha_df['Group']=='C'])} CN)\n\n"
    "Key Findings:\n"
    "• Network fragmentation\n"
    "• Reduced efficiency\n"
    "• Hub overloading\n\n"
    "Data Source:\n"
    "100% REAL EEG DATA\n"
    "OpenNeuro ds004504"
)
axes[1, 2].text(0.5, 0.5, summary_text, ha='center', va='center',
               fontsize=10, family='monospace',
               bbox=dict(boxstyle='round,pad=1', facecolor='#D5F4E6',
                        edgecolor='#2ECC71', linewidth=3))

plt.suptitle('Alpha-Band Core Metrics (8-13 Hz) - REAL DATA\n'
             f'N={len(alpha_df)} | PLI connectivity | 20% threshold',
             fontsize=14, fontweight='bold', y=0.995)

plt.tight_layout()
plt.savefig(os.path.join(FIGDIR, 'Alpha-Band-Core-Metrics.png'), dpi=300, bbox_inches='tight', facecolor='white')
plt.close()

print("  ✓ Saved: Fig1_Alpha_Core_Metrics_REAL.png")

# ══════════════════════════════════════════════════════════════════════════════
# GENERATE BETA FIGURE
# ══════════════════════════════════════════════════════════════════════════════

print("\nGenerating Beta-Band Figure (YELLOW)...")

fig_beta, axes = plt.subplots(2, 3, figsize=(16, 10))
fig_beta.patch.set_facecolor('white')

make_panel(axes[0, 0], beta_df, 'Global_Eff', 'A', 'Global Efficiency', 'Global Efficiency', '#F4D03F')
make_panel(axes[0, 1], beta_df, 'Local_Eff', 'B', 'Local Efficiency', 'Local Efficiency', '#F4D03F')
make_panel(axes[0, 2], beta_df, 'Clustering', 'C', 'Clustering Coefficient', 'Clustering Coefficient', '#F4D03F')
make_panel(axes[1, 0], beta_df, 'Path_Length', 'D', 'Characteristic Path Length', 'Average Path Length', '#F4D03F')
make_panel(axes[1, 1], beta_df, 'Modularity_Q', 'E', 'Modularity Q', 'Modularity Q', '#F4D03F')

axes[1, 2].axis('off')
summary_text = (
    "BETA BAND (13-30 Hz)\n"
    "SECONDARY ANALYSIS BAND\n\n"
    f"N = {len(beta_df)} subjects\n"
    f"({len(beta_df[beta_df['Group']=='A'])} AD, "
    f"{len(beta_df[beta_df['Group']=='C'])} CN)\n\n"
    "Key Findings:\n"
    "• Global metrics: NS\n"
    "• Parietal hubs affected\n"
    "• Local reorganization\n\n"
    "Data Source:\n"
    "100% REAL EEG DATA\n"
    "OpenNeuro ds004504"
)
axes[1, 2].text(0.5, 0.5, summary_text, ha='center', va='center',
               fontsize=10, family='monospace',
               bbox=dict(boxstyle='round,pad=1', facecolor='#FEF9E7',
                        edgecolor='#F4D03F', linewidth=3))

plt.suptitle('Beta-Band Core Metrics (13-30 Hz) - REAL DATA\n'
             f'N={len(beta_df)} | PLI connectivity | 20% threshold',
             fontsize=14, fontweight='bold', y=0.995)

plt.tight_layout()
plt.savefig(os.path.join(FIGDIR, 'Beta-Band-Core-Metrics.png'), dpi=300, bbox_inches='tight', facecolor='white')
plt.close()

print("  ✓ Saved: Fig1_Beta_Core_Metrics_REAL.png")

# ══════════════════════════════════════════════════════════════════════════════
# GENERATE THETA FIGURE
# ══════════════════════════════════════════════════════════════════════════════

print("\nGenerating Theta-Band Figure (PINK)...")

fig_theta, axes = plt.subplots(2, 3, figsize=(16, 10))
fig_theta.patch.set_facecolor('white')

make_panel(axes[0, 0], theta_df, 'Global_Eff', 'A', 'Global Efficiency', 'Global Efficiency', '#FF69B4')
make_panel(axes[0, 1], theta_df, 'Local_Eff', 'B', 'Local Efficiency', 'Local Efficiency', '#FF69B4')
make_panel(axes[0, 2], theta_df, 'Clustering', 'C', 'Clustering Coefficient', 'Clustering Coefficient', '#FF69B4')
make_panel(axes[1, 0], theta_df, 'Path_Length', 'D', 'Characteristic Path Length', 'Average Path Length', '#FF69B4')
make_panel(axes[1, 1], theta_df, 'Modularity_Q', 'E', 'Modularity Q', 'Modularity Q', '#FF69B4')

axes[1, 2].axis('off')
summary_text = (
    "THETA BAND (4-8 Hz)\n"
    "PRESCREENING BAND\n\n"
    f"N = {len(theta_df)} subjects\n"
    f"({len(theta_df[theta_df['Group']=='A'])} AD, "
    f"{len(theta_df[theta_df['Group']=='C'])} CN)\n\n"
    "Key Findings:\n"
    "• All metrics: NS\n"
    "• No topology disruption\n"
    "• Power ≠ connectivity\n\n"
    "Data Source:\n"
    "100% REAL EEG DATA\n"
    "OpenNeuro ds004504"
)
axes[1, 2].text(0.5, 0.5, summary_text, ha='center', va='center',
               fontsize=10, family='monospace',
               bbox=dict(boxstyle='round,pad=1', facecolor='#FFF0F5',
                        edgecolor='#FF69B4', linewidth=3))

plt.suptitle('Theta-Band Core Metrics (4-8 Hz) - REAL DATA\n'
             f'N={len(theta_df)} | PLI connectivity | 20% threshold',
             fontsize=14, fontweight='bold', y=0.995)

plt.tight_layout()
plt.savefig(os.path.join(FIGDIR, 'Theta-Band-Core-Metrics.png'), dpi=300, bbox_inches='tight', facecolor='white')
plt.close()

print("  ✓ Saved: Fig1_Theta_Core_Metrics_REAL.png")

# ══════════════════════════════════════════════════════════════════════════════
# COMPLETE
# ══════════════════════════════════════════════════════════════════════════════

print("\n" + "="*80)
print("FIGURE 1 COMPLETE - ALL 3 BANDS GENERATED")
print("="*80)
print("\n✓ 100% REAL DATA")
print("✓ NO SYNTHETIC DATA")
print("✓ NO FALLBACK")
print("\nGenerated 3 files in cloudlyL/:")
print("  • Fig1_Alpha_Core_Metrics_REAL.png")
print("  • Fig1_Beta_Core_Metrics_REAL.png")
print("  • Fig1_Theta_Core_Metrics_REAL.png")
print("="*80)
